# Generated by Django 5.1.3 on 2024-11-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.TextField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('open', 'Open'), ('close', 'Close')], default='open'),
        ),
    ]
